volumes:
  db:
    driver: local
  pgadmin:
    driver: local
  mailpit:
    driver: local

services:
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_DATABASE: /data/mailpit.db

  db:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build: .
    env_file:
      - db.env
    environment:
      DB_HOST: ${DB_HOST:-db}
    ports:
      - 8080:8080

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - 8081:80
    volumes:
      - pgadmin:/var/lib/pgadmin
